export const restrictionList = [
  'Industrial solvents',
  'Lithium batteries',
  'Magnetized materials',
  'Automobile batteries',
  'Infectioussubstances',
  'Bleach',
  'Flammable adhesives',
  'Dry ice (Carbon Dioxide, Solid)',
  'Dangerous Goods for transport by Air',
  'Alcohol',
  'Tobacco and tobacco related products',
  'Electronic cigarettes',
  'Poison',
  'Ketamine',
  'Foodstuff and liquor',
  'Any pornographic material',
  'Oil-based paint and thinners (flammable liquids)',
  'Insecticides, garden chemicals (fertilizers, poisons)',
  'Uncrossed (bearer) drafts / cheque, currency and coins',
  'Fuel for camp stoves, lanterns, torches or heating elements',
  'Any compound, liquid or gas that has toxic and/or infectious characteristics',
  'Any Aerosols, liquids and/or powders or any other flammable substances classified',
  'Firearms, explosives and military equipment. e. Hazardous and radioactive material',
  'Machinery (chain saws, outboard engines containing fuel or that have contained fuel)',
  'Arms, ammunitions or any weapon with blade (including but not limited to air guns, flares, gunpowder, firework, knives, swords and antique weaponry)',
  'Precious stones, gems and jewellery (including but not limited to antiques bullion (of anyprecious metal), diamonds, gold, silver, platinum, trophies related to animal hunting, semi- precious stones in any form (including bricks)',
  'Any Hazardous chemical items (including but not limited to radioactive material, special chemicals, material, equipments and technologies (SCOMET) items, hazardous/chemical waste, corrosive items (acids), machines parts containing oil, grease, toner)',
  'Any Plants and its related products (including but not limited to oxidizing substances, sand/soils/ores, sandalwood, wood, wood pulp, edible oils, de-oiled groundnut, endangeredspecies of plants and its parts, asbestos)',
  'Any Drugs and Medicines (including but not limited to cocaine, cannabis, LSD, morphine, opium, psychotropic substances, and such other drugs, poisonous goods, contraband (suchasillegal/illicit and counterfeit drugs)',
  'Any Animals and Human Body related items/product (including but not limited to live stock, cremated or disinterred human being’s remains, human being and any animal embryos, humanbeing and any animal remains, human being and any animals corpses, organs/body parts of human being body part.',
]
